name: 'Storybook Deployment'

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: yarn
      - run: |
          yarn install --frozen-lockfile
          git remote set-url origin https://$GH_TOKEN@github.com/alex-kim-dev/storybook-tutorial.git
          npm run deploy-storybook -- --host-token-env-variable=GH_TOKEN
